export const SPANISH: Record<string, string> = {
  'Right-click capture': 'Captura con clic derecho',
  'Select text, or right-click links and images into the panel.': 'Selecciona texto o haz clic derecho en enlaces e imágenes para guardarlos en el panel.',
  'Alt+S shortcut': 'Atajo Alt+S',
  'Highlight text and press Alt+S to save without opening a menu.': 'Selecciona texto y pulsa Alt+S para guardarlo sin abrir un menú.',
  'Type, date & site filters': 'Filtros por tipo, fecha y sitio',
  'Filter by type, time range, or site to find items fast.': 'Filtra por tipo, fecha o sitio para encontrar tus elementos rápidamente.',
  'Flexible copy formats': 'Varios formatos de copia',
  'Plain text, Markdown, or with source context attached.': 'Copia como texto sin formato, Markdown o con la fuente incluida.',
  'Pin & multi-select': 'Fijar y seleccionar varios',
  'Pin important cards. Batch copy, cut, or delete.': 'Fija lo importante. Copia, corta o elimina varios elementos a la vez.',
  'Image ZIP download': 'Descarga de imágenes en ZIP',
  'Select images and download them as a single ZIP.': 'Selecciona imágenes y descárgalas en un solo archivo ZIP.',
  'Features': 'Funciones',
  'A light tool for heavy browsers.': 'Una herramienta ligera para quienes navegan mucho.',
  'Same quiet UI as the extension — clean, restrained, out of the way.': 'La misma interfaz discreta de la extensión: limpia, sencilla y sin interrumpirte.',
  'Ready to stash as you browse?': '¿Listo para guardar lo que encuentras?',
  'Chrome extension · free · MIT': 'Extensión de Chrome · Gratis · MIT',
  'Add to Chrome': 'Añadir a Chrome',
  'Chrome Web Store': 'Chrome Web Store',
  'Primary': 'Navegación principal',
  'Try it': 'Probar',
  'How it works': 'Cómo funciona',
  'Privacy': 'Privacidad',
  'Language': 'Idioma',
  'Toggle theme': 'Cambiar tema',
  'Install': 'Instalar',
  'Browser side-panel collector': 'Colecciona en el panel lateral',
  'Stash it.': 'Guárdalo.',
  'Find it.': 'Encuéntralo.',
  'Right-click text, links, or images into a private side panel. Search, filter, multi-select, copy — all local, no account.': 'Guarda texto, enlaces e imágenes con clic derecho. Busca, filtra y copia en un panel privado. Todo local, sin cuenta.',
  'Add to Chrome — free': 'Añadir a Chrome · Gratis',
  'Try it here': 'Pruébalo aquí',
  'Local only': 'Solo almacenamiento local',
  'Real side-panel UI · search, filter, pin, copy': 'Panel real · Busca, filtra, fija y copia',
  '01 · Capture': '01 · Capturar',
  'Right-click, or press Alt+S': 'Clic derecho o Alt+S',
  'Select text, or right-click a link or image. Save without leaving the page.': 'Selecciona texto o haz clic derecho en un enlace o imagen. Guarda sin salir de la página.',
  '02 · Review': '02 · Revisar',
  'Open the focused side panel': 'Revisa todo en el panel lateral',
  'Text, links, and images stay grouped with source context. Pin what matters.': 'Texto, enlaces e imágenes conservan su fuente. Fija lo que importa.',
  '03 · Reuse': '03 · Reutilizar',
  'Search, multi-select, copy': 'Busca, selecciona y copia',
  'Filter by type, date, or site. Copy as plain text, Markdown, or with source.': 'Filtra por tipo, fecha o sitio. Copia como texto, Markdown o con la fuente.',
  'Workflow': 'Flujo de trabajo',
  'A small capture loop that stays out of the way.': 'Guarda y reutiliza sin interrupciones.',
  'Built for the tiny things you do not want to lose while reading or researching.': 'Para esas pequeñas cosas que no quieres perder mientras lees o investigas.',
  'Shortcut:': 'Atajo:',
  'saves the current selection': 'guarda el texto seleccionado',
  'Side Stash keeps page fragments in a local side panel — text, links, and images, ready to search and copy.': 'Side Stash reúne texto, enlaces e imágenes de la web en un panel lateral local, listos para buscar y copiar.',
  'Minimal architectural space': 'Espacio arquitectónico minimalista',
  'Demo article': 'Artículo de ejemplo',
  'Select text first, then press the shortcut.': 'Selecciona texto primero y después pulsa el atajo.',
  'Live playground': 'Demostración interactiva',
  'No install needed — try the real panel UI.': 'Prueba el panel real sin instalar nada.',
  'Left: a mock page — select text then right-click or press Alt+S; right-click images/links too. Right: the real side-panel UI.': 'A la izquierda, selecciona texto y haz clic derecho o pulsa Alt+S. También puedes guardar imágenes y enlaces. A la derecha está el panel real.',
  'Reset demo': 'Reiniciar demo',
  'Select text, then right-click or press ': 'Selecciona texto y haz clic derecho o pulsa ',
  ' · or right-click image / link': ' · O haz clic derecho en una imagen o enlace',
  'Text snippet': 'Fragmento de texto',
  'Save': 'Guardar',
  'Image': 'Imagen',
  'Link': 'Enlace',
  'Copy': 'Copiar',
  'Look Up “selection”': 'Consultar la selección',
  'Inspect': 'Inspeccionar',
  'Starts empty · Alt+S or right-click saves land here': 'Empieza vacío · Lo que guardes con Alt+S o clic derecho aparecerá aquí',
  'Saves only on your device, in your browser': 'Se guarda solo en el navegador de tu dispositivo',
  'No account, no sign-up': 'Sin cuenta ni registro',
  'No analytics or tracking scripts': 'Sin análisis ni scripts de seguimiento',
  'Export everything anytime for backup': 'Exporta todo cuando quieras para hacer una copia',
  'Stays on your device.': 'Se queda en tu dispositivo.',
  'Nothing is uploaded to a cloud account. Your stash lives in your browser on this device — only you can see it.': 'Nada se sube a una cuenta en la nube. Tu colección permanece en el navegador de este dispositivo y solo tú puedes verla.',
  'Demo page': 'Página de ejemplo',
  'Image saved': 'Imagen guardada',
  'Link saved': 'Enlace guardado',
  'Text saved': 'Texto guardado',
  'Demo data reset': 'Demostración reiniciada',
  'Select items first': 'Selecciona elementos primero',
  'Nothing to copy': 'No hay nada que copiar',
  'Copied to clipboard': 'Copiado al portapapeles',
  'Copy failed': 'No se pudo copiar',
  'Deleted': 'Eliminado',
  'Undo': 'Deshacer',
  'Demo: ZIP download': 'Demo: descarga ZIP',
  'Demo: download images': 'Demo: descarga de imágenes',
  'Demo: export JSON': 'Demo: exportación JSON',
  'Demo: export Markdown': 'Demo: exportación Markdown',
  'Loaded sample items': 'Ejemplos cargados',
  'Demo cleared': 'Demostración vaciada',
  'Demo: download image': 'Demo: descarga de imagen',
};
