import type { SavedItem } from '../types';

export const MOCK_ITEMS: SavedItem[] = [
  {
    id: 'mock-1',
    type: 'text',
    content: 'const stance = { design: "monochrome", architecture: "clean" };',
    pageTitle: 'Side Stash Architecture Manifesto',
    pageUrl: 'https://github.com/LanrenwenStudio/side-stash',
    createdAt: new Date().toISOString(),
    pinned: true,
  },
  {
    id: 'mock-2',
    type: 'link',
    content: 'Tailwind CSS Documentation — Rapidly build modern websites',
    linkUrl: 'https://tailwindcss.com/docs/installation',
    pageTitle: 'Tailwind CSS Docs',
    pageUrl: 'https://tailwindcss.com',
    createdAt: new Date(Date.now() - 1800 * 1000).toISOString(),
    pinned: true,
  },
  {
    id: 'mock-3',
    type: 'image',
    content: 'Architectural Minimalist Interior Space',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop',
    imageAlt: 'Modern Minimalist Architectural Space',
    pageTitle: 'Architectural Digest - Minimalist Design',
    pageUrl: 'https://unsplash.com',
    createdAt: new Date(Date.now() - 7200 * 1000).toISOString(),
    pinned: false,
  },
  {
    id: 'mock-4',
    type: 'text',
    content: 'Simplification is not about stripping away features; it is about clarifying intent and scope.',
    pageTitle: 'Essays on Software Design',
    pageUrl: 'https://developer.mozilla.org',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    pinned: false,
  },
  {
    id: 'mock-5',
    type: 'link',
    content: 'React 19 Official Release & Component Optimization Guide',
    linkUrl: 'https://react.dev/blog/2024/12/05/react-19',
    pageTitle: 'React.dev Official Blog',
    pageUrl: 'https://react.dev',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000 * 2).toISOString(),
    pinned: false,
  },
  {
    id: 'mock-6',
    type: 'image',
    content: 'Monochrome Typography Print Composition',
    imageUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=800&auto=format&fit=crop',
    imageAlt: 'Black and White Typography Print',
    pageTitle: 'Graphic Design Showcase',
    pageUrl: 'https://unsplash.com',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000 * 3).toISOString(),
    pinned: false,
  },
  {
    id: 'mock-7',
    type: 'text',
    content: 'npm run build && npm run dev — Extension recompiled & dev server running cleanly.',
    pageTitle: 'Side Stash Developer Agent Notes',
    pageUrl: 'https://github.com/LanrenwenStudio/side-stash',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000 * 5).toISOString(),
    pinned: false,
  },
];
